services:
  app-service:
    build:
      context: app
      dockerfile: .
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./app:/app-service
    environment:
      PORT: 80
      ML_Server: http://172.17.0.1:5000/

  poke-ml-service:
    build: .
    ports:
      - "5000:5000"
    restart: always
