services:
  app-service:
    build:
      context: app
      dockerfile: .
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./app:/app-service
    environment:
      PORT: 80
      ML_Server: "http://172.18.0.3:5000/"

  poke-ml-service:
    build: Dockerfile
    ports:
      - "5000:5000"
    restart: always
