services:
  app-service:
    build: app/.
    volumes:
      - ./app:/app-service
    ports:
      - "80:80"
    environment:
      PORT: "80"
      ML_Server: "http://172.17.0.1:5000/"

  poke-ml-service:
    build: .
    volumes:
      - ./ML_Model_Serving:/ml-service/ML_Model_Serving
    ports:
      - "5000:5000"
